Telescope.strings.pl = {
  "forms.submit": "Zatwierdź",
  "forms.cancel": "Anuluj",

  "posts.new_post": "Nowy wpis",
  "posts.edit": "Edytuj",
  "posts.edit_success": "Wpis “{title}” został zmieniony.",
  "posts.delete": "Usuń",
  "posts.delete_confirm": "Czy usunąć wpis “{title}”?",
  "posts.delete_success": "Wpis “{title}” został usunięty.",
  "posts.title": "Tytuł",
  "posts.url": "Adres URL",
  "posts.body": "Treść",
  "posts.categories": "Kategorie",
  "posts.thumbnailUrl": "Adres URL Miniaturki",
  "posts.status": "Status",
  "posts.sticky": "Przytwierdzony",
  "posts.load_more": "Wczytaj Więcej",
  "posts.search": "Szukaj",
  "posts.view": "Widok",
  "posts.top": "Aktywne",
  "posts.new": "Nowe",
  "posts.best": "Najlepsze",
  "posts.pending": "Oczekujące",
  "posts.rejected": "Odrzucone",
  "posts.scheduled": "Zaplanowane",
  "posts.daily": "Dziennie",
  "posts.clear_thumbnail": "Wyczyść Miniaturkę",
  "posts.enter_thumbnail_url": "Wprowadź Adres URL",
  "posts.created_message": "Wpis utworzony.",
  "posts.rate_limit_error": "Proszę zaczekaj {details} sekund zanim dodasz kolejny wpis.",
  "posts.postedAt": "Opublikowano",
  "posts.dateNotDefined": "Brak daty",

  "comments.comments": "Komentarze",
  "comments.count": "{count, plural, =0 {Brak komentarzy} one {# komentarz} other {# komantarzy}}",
  "comments.new": "Nowy komentarz",
  "comments.no_comments": "Brak komentarzy do wyświetlenia.",
  "comments.reply": "Odpowiedz",
  "comments.edit": "Edytuj",
  "comments.delete": "Usuń",
  "comments.delete_confirm": "Usunąć komentarz “{body}”?",
  "comments.delete_success": "Komentarz “{body}” usunięty.",
  "comments.please_log_in": "Zaloguj się, aby komentować.",
  "comments.parentCommentId": "ID Nadrzędnego Komentarza",
  "comments.topLevelCommentId": "ID Pierwszego Komentarza",
  "comments.body": "Treść",
  "comments.rate_limit_error": "Proszę zaczekaj {details} sekund zanim dodasz kolejny komentarz.",

  "users.profile": "Profil",
  "users.complete_profile": "Uzupełnij swój Profil",
  "users.edit_account": "Edytuj Konto",
  "users.log_in": "Zaloguj",
  "users.log_out": "Wyloguj",
  "users.telescope.bio": "O mnie",
  "users.telescope.displayName": "Wyświetlana nazwa",
  "users.telescope.email": "Email",
  "users.telescope.twitterUsername": "Nazwa Konta Twitter",
  "users.telescope.website": "Strona WWW",
  "users.notifications": "Powiadomienia",
  "users.telescope.notifications_users": "Powiadomienia o Nowych Użytkownikach",
  "users.telescope.notifications_posts": "Powiadomienia o Nowych Wpisach",
  "users.telescope.newsletter_subscribeToNewsletter": "Zapisz do newslettera",
  "users.admin": "Administracja",
  "users.isAdmin": "Administrator",
  "users.posts": "Wpisy",
  "users.please_log_in": "Zaloguj się",
  "users.cannot_post": "Przepraszamy, brak uprawnień do tworzenia wpisów w tej chwili",

  "categories": "Kategorie",
  "categories.all": "Wszystkie Kategorie",
  "categories.edit": "Edytuj Kategorię",
  "categories.new": "Nowa Kategoria",
  "categories.delete": "Usuń Kategorię",
  "categories.name": "Nazwa",
  "categories.description": "Opis",
  "categories.order": "Kolejność",
  "categories.slug": "Uproszczona nazwa",
  "categories.image": "Obrazek",
  "categories.parentId": "Nadrzędne ID",

  "settings": "Ustawienia",
  "settings.json_message": "Uwaga: ustawienia podane w pliku <code>settings.json</code> będą nieaktywne.",
  "settings.edit": "Edytuj Ustawienia",
  "settings.edited": "Ustawienia zostały zapisane (odświerz stronę).",
  "settings.title": "Tytuł",
  "settings.siteUrl": "Adres URL Strony",
  "settings.tagline": "Slogan",
  "settings.description": "Opis",
  "settings.siteImage": "Obrazek Strony",
  "settings.defaultEmail": "Domyślny Email",
  "settings.mailUrl": "Adres URL Maila",
  "settings.scoreUpdate": "Aktualizacja Wyników",
  "settings.postInterval": "Czas Pomiędzy Wpisami",
  "settings.RSSLinksPointTo": "Linki RSS Wskazują Do",
  "settings.commentInterval": "Czas Pomiędzy Komantarzami",
  "settings.maxPostsPerDay": "Maksymalna Dzienna Ilość Postów",
  "settings.startInvitesCount": "Liczenie Zaproszeń",
  "settings.postsPerPage": "Wpisów Na Stronie",
  "settings.logoUrl": "Adres URL Logo",
  "settings.logoHeight": "Wysokość Logo",
  "settings.logoWidth": "Szerokość Logo",
  "settings.faviconUrl": "Adres URL Favicon",
  "settings.twitterAccount": "Konto Twitter",
  "settings.facebookPage": "Strona Facebook",
  "settings.googleAnalyticsId": "ID Google Analytics",
  "settings.locale": "Ustawienia Regionalne",
  "settings.requireViewInvite": "Wymagaj Zaproszenia aby Przeglądać",
  "settings.requirePostInvite": "Wymagaj Zaproszenia aby Dodawać Wpisy",
  "settings.requirePostsApproval": "Wymagaj Zatwierdzania Wpisów",
  "settings.scoreUpdateInterval": "Czas Pomiędzy Aktualizacją Wyników",

  "app.loading": "Wczytywanie…",
  "app.404": "Przykro nam, ale nie możemy znaleźć tego czego szukasz.",
  "app.powered_by": "Wspierany przez Telescope",
  "app.or": "Lub",

  "newsletter": "Newsletter",
  "newsletter.subscribe": "Subskrybuj",
  "newsletter.unsubscribe": "Zakończ Subskrypcję",
  "newsletter.subscribe_prompt": "Subskrybuj newsletter",
  "newsletter.email": "Twój email",
  "newsletter.success_message": "Dziękujemy za subskrybcję!",

  "admin": "Administrator",
  "notifications": "Powiadomienia",
}
