Telescope.strings.pl = {
  "forms.submit": "Zatwierdź",
  "forms.cancel": "Anuluj",

  "posts.new_post": "Nowy wpis",
  "posts.edit": "Edytuj",
  "posts.edit_success": "Wpis “{title}” został edytowany.",
  "posts.delete": "Usuń",
  "posts.delete_confirm": "Usunąć wpis “{title}”?",
  "posts.delete_success": "Wpis “{title}” usunięty.",
  "posts.title": "Tytuł",
  "posts.url": "URL",
  "posts.body": "Treść",
  "posts.categories": "Kategorie",
  "posts.thumbnailUrl": "Miniaturka URL",
  "posts.status": "Status",
  "posts.sticky": "Przytwierdzony",
  "posts.load_more": "Wczytaj więcej",
  "posts.search": "Szukaj",
  "posts.view": "Widok",
  "posts.top": "Góra",
  "posts.new": "Nowy",
  "posts.best": "Najlepsze",
  "posts.pending": "Oczekujące",
  "posts.rejected": "Odrzucone",
  "posts.scheduled": "Zaplanowane",
  "posts.daily": "Dziennie",
  "posts.clear_thumbnail": "Wyczyść Miniaturkę",
  "posts.enter_thumbnail_url": "Wprowadź URL",
  "posts.created_message": "Wpis utworzony.",
  "posts.rate_limit_error": "Zaczekaj {details} sekund zanim dodasz kolejny wpis.",

  "comments.comments": "Comments",
  "comments.count": "{count, plural, =0 {No comments} one {# comment} other {# comments}}",
  "comments.new": "New Comment",
  "comments.no_comments": "No comments to display.",
  "comments.reply": "Reply",
  "comments.edit": "Edit",
  "comments.delete": "Delete",
  "comments.delete_confirm": "Delete comment “{body}”?",
  "comments.delete_success": "Comment “{body}” deleted.",
  "comments.please_log_in": "Please log in to comment.",
  "comments.parentCommentId": "Parent Comment ID",
  "comments.topLevelCommentId": "Top Level Comment ID",
  "comments.body": "Body",
  "comments.rate_limit_error": "Please wait {details} seconds before commenting again.",

  "users.profile": "Profile",
  "users.complete_profile": "Complete your Profile",
  "users.edit_account": "Edit Account",
  "users.log_in": "Log In",
  "users.log_out": "Log Out",
  "users.telescope.bio": "Bio",
  "users.telescope.displayName": "Display Name",
  "users.telescope.email": "Email",
  "users.telescope.twitterUsername": "Twitter Username",
  "users.telescope.website": "Website",
  "users.notifications": "Notifications",
  "users.telescope.notifications_users": "New Users Notifications",
  "users.telescope.notifications_posts": "New Posts Notifications",
  "users.telescope.newsletter_subscribeToNewsletter": "Subscribe to newsletter",
  "users.admin": "Admin",
  "users.isAdmin": "Admin",
  "users.posts": "Posts",
  "users.please_log_in": "Please log in",
  "users.cannot_post": "Sorry, you do not have permissions to post at this time",

  "categories": "Categories",
  "categories.all": "All Categories",
  "categories.edit": "Edit Category",
  "categories.new": "New Category",
  "categories.delete": "Delete Category",
  "categories.name": "Name",
  "categories.description": "Description",
  "categories.order": "Order",
  "categories.slug": "Slug",
  "categories.image": "Image",
  "categories.parentId": "Parent ID",

  "settings": "Settings",
  "settings.json_message": "Note: settings already provided in your <code>settings.json</code> file will be disabled.",
  "settings.edit": "Edit Settings",
  "settings.edited": "Settings edited (please reload).",
  "settings.title": "Title",
  "settings.siteUrl": "Site URL",
  "settings.tagline": "Tagline",
  "settings.description": "Description",
  "settings.siteImage": "Site Image",
  "settings.defaultEmail": "Default Email",
  "settings.mailUrl": "Mail URL",
  "settings.scoreUpdate": "Score Update",
  "settings.postInterval": "Post Interval",
  "settings.RSSLinksPointTo": "RSS Links Point To",
  "settings.commentInterval": "Comment Interval",
  "settings.maxPostsPerDay": "Max Posts Per Day",
  "settings.startInvitesCount": "Start Invites Count",
  "settings.postsPerPage": "Posts Per Page",
  "settings.logoUrl": "Logo URL",
  "settings.logoHeight": "Logo Height",
  "settings.logoWidth": "Logo Width",
  "settings.faviconUrl": "Favicon URL",
  "settings.twitterAccount": "Twitter Account",
  "settings.facebookPage": "Facebook Page",
  "settings.googleAnalyticsId": "Google Analytics ID",
  "settings.locale": "Locale",
  "settings.requireViewInvite": "Require View Invite",
  "settings.requirePostInvite": "Require Post Invite",
  "settings.requirePostsApproval": "Require Posts Approval",
  "settings.scoreUpdateInterval": "Score Update Interval",

  "app.loading": "Loading…",
  "app.404": "Sorry, we couldn't find what you were looking for.",
  "app.powered_by": "Powered by Telescope",
  "app.or": "Or",

  "newsletter": "Newsletter",
  "newsletter.subscribe": "Subscribe",
  "newsletter.unsubscribe": "Unsubscribe",
  "newsletter.subscribe_prompt": "Subscribe to the newsletter",
  "newsletter.email": "Your email",
  "newsletter.success_message": "Thanks for subscribing!",

  "admin": "Admin",
  "notifications": "Notifications",
}
